export const categoryColors = {
  'Food': '#FF6B6B',
  'Social Life': '#4ECDC4',
  'Entertainment': '#45B7D1',
  'Fuel': '#FFA726',
  'Culture': '#66BB6A',
  'Household': '#42A5F5',
  'Apparel': '#AB47BC',
  'Beauty': '#EC407A',
  'Health': '#26A69A',
  'Education': '#5C6BC0',
  'Transportation': '#78909C',
  'Vyomi': '#26C6DA',
  'Vacation': '#FF7043',
  'Subscriptions': '#9CCC65',
  'Misc': '#8D6E63',
  'Income': '#66BB6A'
};

export const masterCategories = [
  { main: 'Food', sub: 'Food', combined: 'Food > Food' },
  { main: 'Fuel', sub: 'Honda City', combined: 'Fuel > Honda City' },
  { main: 'Fuel', sub: 'Aviator', combined: 'Fuel > Aviator' },
  { main: 'Fuel', sub: 'Eon', combined: 'Fuel > Eon' },
  { main: 'Culture', sub: 'Culture', combined: 'Culture > Culture' },
  { main: 'Household', sub: 'Grocery', combined: 'Household > Grocery' },
  { main: 'Household', sub: 'Laundry', combined: 'Household > Laundry' },
  { main: 'Household', sub: 'House Help', combined: 'Household > House Help' },
  { main: 'Household', sub: 'Appliances', combined: 'Household > Appliances' },
  { main: 'Household', sub: 'Bills', combined: 'Household > Bills' },
  { main: 'Apparel', sub: 'Apparel', combined: 'Apparel > Apparel' },
  { main: 'Beauty', sub: 'Beauty', combined: 'Beauty > Beauty' },
  { main: 'Health', sub: 'Preventive', combined: 'Health > Preventive' },
  { main: 'Health', sub: 'Medical', combined: 'Health > Medical' },
  { main: 'Education', sub: 'Education', combined: 'Education > Education' },
  { main: 'Transportation', sub: 'Maintenance', combined: 'Transportation > Maintenance' },
  { main: 'Transportation', sub: 'Insurance', combined: 'Transportation > Insurance' },
  { main: 'Vyomi', sub: 'Vyomi', combined: 'Vyomi > Vyomi' },
  { main: 'Vacation', sub: 'Family', combined: 'Vacation > Family' },
  { main: 'Vacation', sub: 'Own', combined: 'Vacation > Own' },
  { main: 'Subscriptions', sub: 'Subscriptions', combined: 'Subscriptions > Subscriptions' },
  { main: 'Misc', sub: 'Misc', combined: 'Misc > Misc' },
  { main: 'Income', sub: 'Income', combined: 'Income > Income' },
  { main: 'Income', sub: 'Reload', combined: 'Income > Reload' },
  { main: 'Income', sub: 'Others', combined: 'Income > Others' },
  { main: 'Social Life', sub: 'Social Life', combined: 'Social Life > Social Life' },
  { main: 'Entertainment', sub: 'Entertainment', combined: 'Entertainment > Entertainment' }
];
